apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgeclient
spec:
  selector:
    matchLabels:
      app: edgeclient
  replicas: 1
  template:
    metadata:
      labels:
        app: edgeclient
  
    spec:
      hostname: edgeclient
      containers:
      - name: edgeclient
        image: rgarb12/edgeclient
        imagePullPolicy: Always
