apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  type: NodePort
  ports:
    - port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    app: kafka
---
apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 3 
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: sumglobal/rpi-kafka
        imagePullPolicy: Always
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: 10.38.0.3:2181
        - name: ZOOKEEPER_CONNECTION_STRING 
          value: 10.38.0.3:2181
        - name: HOSTNAME_COMMAND
          value: "route -n | awk '/UG[ \t]/{print $2}'"
        - name: KAFKA_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_HEAP_OPTS
          value: "-Xmx256M -Xms128M"
        - name: KAFKA_CREATE_TOPICS
          value: "Topic2:1:1:compact"
        ports:
        - containerPort: 9092
          protocol: TCP
