apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-broker
spec:
  selector:
    matchLabels:
      app: mqtt
  replicas: 1
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      containers:
      - name: eclipse-mosquitto
        image: eclipse-mosquitto:1.6.7
        ports:
          - containerPort: 1883
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-broker-service
spec:
  type: NodePort
  selector:
    app: mqtt
  ports:
  - protocol: TCP
    port: 1883
    targetPort: 1883
