apiVersion: apps/v1
kind: Deployment
metadata:
  name: communication
spec:
  selector:
    matchLabels:
      app: communication
  replicas: 1
  template:
    metadata:
      labels:
        app: communication
    spec:
      containers:
      - name: communication-service
        image: cliftonf87/communication-service
        ports:
          - containerPort: 5000
        env:
        - name: KAFKA_SERVER1
          value: kafka-service:9092
        - name: KAFKA_SERVER2
          value: kafka-service:9092
        - name: KAFKA_SERVER3
          value: kafka-service:9092
        - name: MQTT_BROKER
          value: mqtt-broker-service
---
apiVersion: v1
kind: Service
metadata:
  name: communication-service
spec:
  selector:
    app: communication
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000

